name: Deploy to S3

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-2
  BUCKET_NAME: www.askmimir.net

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy to S3 bucket
        run: aws s3 sync ./dist/ s3://BUCKET_NAME --delete